// next.config.js
module.exports = {
  env: {
    NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY,
    NEXT_PUBLIC_EMAILJS_SERVICE_ID: process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID,
    NEXT_PUBLIC_EMAILJS_COUPON_TEMPLATE_ID:
      process.env.NEXT_PUBLIC_EMAILJS_COUPON_TEMPLATE_ID,
    NEXT_PUBLIC_EMAILJS_COMMENT_TEMPLATE_ID:
      process.env.NEXT_PUBLIC_EMAILJS_COMMENT_TEMPLATE_ID,
  },
  // ... otras configuraciones si las tienes
};
